# Generated by Django 3.2.15 on 2022-08-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorteners', '0003_rename_urls_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
